"""Loss functions for confidence and tempo distribution heads."""

from __future__ import annotations

import torch
import torch.nn as nn
import torch.nn.functional as F


class ConfidenceLoss(nn.Module):
    """Binary cross-entropy loss for confidence prediction.

    Target: binary correctness mask (1 = backbone prediction is correct, 0 = incorrect).
    Generated by comparing backbone beat predictions against ground-truth positions
    with a 50ms tolerance window.
    """

    def __init__(self, pos_weight: float = 1.0) -> None:
        super().__init__()
        self.pos_weight = torch.tensor([pos_weight])

    def forward(
        self,
        confidence: torch.Tensor,
        correctness_mask: torch.Tensor,
    ) -> torch.Tensor:
        """
        Args:
            confidence: [B, T] predicted confidence in [0, 1]
            correctness_mask: [B, T] binary ground truth

        Returns:
            Scalar loss
        """
        return F.binary_cross_entropy(
            confidence,
            correctness_mask,
            weight=None,
        )


class TempoDistributionLoss(nn.Module):
    """Cross-entropy loss for tempo distribution prediction.

    Target: soft label from ground-truth tempo with Gaussian smoothing.
    This allows the model to learn that nearby BPM bins are "almost right"
    rather than treating tempo prediction as a hard classification problem.
    """

    def __init__(self, sigma_bpm: float = 2.0) -> None:
        super().__init__()
        self.sigma_bpm = sigma_bpm

    def forward(
        self,
        tempo_distribution: torch.Tensor,
        target_bpm: torch.Tensor,
        bpm_bins: torch.Tensor,
    ) -> torch.Tensor:
        """
        Args:
            tempo_distribution: [B, T, n_bins] predicted distribution
            target_bpm: [B, T] ground-truth BPM per frame
            bpm_bins: [n_bins] BPM value for each bin

        Returns:
            Scalar loss (KL divergence)
        """
        # Create soft targets with Gaussian smoothing around true BPM
        # [B, T, 1] - [n_bins] -> [B, T, n_bins]
        diff = bpm_bins.unsqueeze(0).unsqueeze(0) - target_bpm.unsqueeze(-1)
        soft_target = torch.exp(-0.5 * (diff / self.sigma_bpm) ** 2)
        soft_target = soft_target / soft_target.sum(dim=-1, keepdim=True).clamp(min=1e-8)

        # KL divergence
        log_pred = torch.log(tempo_distribution.clamp(min=1e-8))
        return F.kl_div(log_pred, soft_target, reduction="batchmean")


class CombinedLoss(nn.Module):
    """Weighted combination of all head losses.

    L = lambda_conf * L_confidence + lambda_tempo * L_tempo
    """

    def __init__(
        self,
        lambda_conf: float = 1.0,
        lambda_tempo: float = 0.5,
    ) -> None:
        super().__init__()
        self.confidence_loss = ConfidenceLoss()
        self.tempo_loss = TempoDistributionLoss()
        self.lambda_conf = lambda_conf
        self.lambda_tempo = lambda_tempo

    def forward(
        self,
        predictions: dict[str, torch.Tensor],
        targets: dict[str, torch.Tensor],
    ) -> dict[str, torch.Tensor]:
        """
        Args:
            predictions: Model output dict with 'confidence', 'tempo_distribution'
            targets: Target dict with 'correctness_mask', 'target_bpm', 'bpm_bins'

        Returns:
            Dict with 'total', 'confidence', 'tempo' losses
        """
        l_conf = self.confidence_loss(
            predictions["confidence"],
            targets["correctness_mask"],
        )
        l_tempo = self.tempo_loss(
            predictions["tempo_distribution"],
            targets["target_bpm"],
            targets["bpm_bins"],
        )

        total = self.lambda_conf * l_conf + self.lambda_tempo * l_tempo

        return {
            "total": total,
            "confidence": l_conf,
            "tempo": l_tempo,
        }
